controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_index:
  path: /
  methods: [GET, POST]
  controller: 'App\Controller\MainController::index'
